"""R1: Regime Dominance Gate — meta-rule for boundary-activated grammar chains.

## Motivation

A grammar chain is "boundary-activated" when its evidence is in the minimal /
borderline zone: the chain cleared its minimum threshold, but the evidence is
not strong enough to be clearly dominant on its own.  When a contradicting regime
simultaneously shows *strong* signals (e.g. funding_extreme + OI_accumulation),
the weak chain activation is overridden by the dominant context.

Suppressing boundary-activated chains under dominant contradicting regimes prevents:
  - hypothesis cards that will immediately conflict with stronger-evidence cards
  - downstream reject_conflicted decisions and spurious reroutes

## What this module provides

  R1PolicySpec      — formal specification for one R1 instance (dataclass)
  RegimeDominanceChecker — stateless evaluator; call should_suppress(...)
  apply_r1          — convenience one-call interface for chain builders
  regime_dominance_gate — decorator factory for declarative R1 on chain fns

## Built-in regime signal resolvers

The decorator and apply_r1 can resolve these signal names automatically:
  "funding_extreme"   — any FundingNode(is_extreme=True) for the pair's assets
  "oi_accumulation"   — any OIState(is_accumulation=True) in collections

Additional signals can be registered via register_regime_resolver().

## Usage patterns

Pattern 1 — inline (J1-style):

    from ..kg.regime_dominance_gate import apply_r1, R1PolicySpec

    _MY_R1_SPEC = R1PolicySpec(
        chain_type="e1_transient_aggression",
        regime_signals=["funding_extreme", "oi_accumulation"],
        ...
    )

    def _my_chain(kg, merged_kg, collections, a1, a2, corr_nid, break_score, log):
        if apply_r1(_MY_R1_SPEC, merged_kg, collections, [a1, a2], f"{a1}/{a2}", log):
            return
        ...  # normal chain logic

Pattern 2 — declarative decorator (future chains):

    @regime_dominance_gate(
        chain_type="future_chain",
        regime_signals=["funding_extreme"],
        contradicting_outcome="positioning_unwind",
    )
    def _future_chain(kg, merged_kg, collections, a1, a2, corr_nid, break_score, log):
        ...  # R1 check runs automatically before this body
"""

import functools
from dataclasses import dataclass, field
from typing import Callable

from ..kg.base import KGraph


# ---------------------------------------------------------------------------
# R1PolicySpec — formal specification
# ---------------------------------------------------------------------------

@dataclass
class R1PolicySpec:
    """Formal specification for a single R1 (Regime Dominance Gate) instance.

    Attributes:
        chain_type: Chain identifier, e.g. "e1_transient_aggression".
            Used as the "chain" key in suppression log entries.
        regime_signals: Ordered list of regime signal names that constitute
            the dominant contradicting regime. Built-in signals: see module
            docstring. Register custom signals with register_regime_resolver().
        regime_combinator: "AND" — all signals must be present (default);
            "OR" — any single signal is sufficient.
        expected_outcome: Branch/outcome the chain normally produces.
            Informational; stored in suppression log for auditability.
        contradicting_outcome: Outcome that dominates when regime is present.
            Informational; stored in suppression log.
        suppression_reason: Human-readable text embedded in the suppression
            log detail field.  Autogenerated from regime_signals if empty.
        log_tag: Suppression log key that marks an R1-triggered entry.
            Defaults to "r1_regime_dominance_gate" so callers can filter R1
            entries without inspecting detail text.
    """
    chain_type: str
    regime_signals: list = field(default_factory=list)
    regime_combinator: str = "AND"
    expected_outcome: str = ""
    contradicting_outcome: str = ""
    suppression_reason: str = ""
    log_tag: str = "r1_regime_dominance_gate"

    def __post_init__(self) -> None:
        if self.regime_combinator not in ("AND", "OR"):
            raise ValueError(
                f"regime_combinator must be 'AND' or 'OR', got {self.regime_combinator!r}"
            )
        if not self.suppression_reason:
            joined = " + ".join(self.regime_signals)
            self.suppression_reason = (
                f"{joined} present — chain suppressed by regime dominance (R1)"
            )


# ---------------------------------------------------------------------------
# Regime signal resolvers (built-in)
# ---------------------------------------------------------------------------

# Registry: signal_name → fn(merged_kg, collections, assets) → bool
_REGIME_RESOLVERS: dict[str, Callable] = {}


def register_regime_resolver(signal_name: str) -> Callable:
    """Register a resolver function for a named regime signal.

    Decorated function signature:
        fn(merged_kg: KGraph, collections: dict, assets: list[str]) -> bool

    Returns the function unchanged (for stacking decorators).
    """
    def decorator(fn: Callable) -> Callable:
        _REGIME_RESOLVERS[signal_name] = fn
        return fn
    return decorator


@register_regime_resolver("funding_extreme")
def _resolve_funding_extreme(
    merged_kg: KGraph, collections: dict, assets: list
) -> bool:
    """True if any FundingNode(is_extreme=True) exists for the given assets.

    Why duplicated from chain_grammar helpers:
      regime_dominance_gate.py must not import chain_grammar.py (circular dep
      because chain_grammar imports this module for R1PolicySpec / apply_r1).
      The resolver only needs KGraph base types, which are safe to import.
    """
    asset_set = set(assets)
    return any(
        n.node_type == "FundingNode"
        and n.attributes.get("is_extreme")
        and len(n.node_id.split(":")) >= 2
        and n.node_id.split(":")[1] in asset_set
        for n in merged_kg.nodes.values()
    )


@register_regime_resolver("oi_accumulation")
def _resolve_oi_accumulation(
    merged_kg: KGraph, collections: dict, assets: list
) -> bool:
    """True if any OIState(is_accumulation=True) exists for the given assets.

    Why here and not chain_grammar:
      Same circular-dep reason as _resolve_funding_extreme above.
    """
    return any(
        s.is_accumulation
        for a in assets
        if (coll := collections.get(a))
        for s in coll.oi_states
    )


def resolve_regime_states(
    signals: list,
    merged_kg: KGraph,
    collections: dict,
    assets: list,
) -> dict:
    """Resolve a list of signal names to {signal: bool} using registered resolvers.

    Unknown signal names resolve to False and are silently skipped so that
    callers can experiment with custom signals without crashing the pipeline.

    Args:
        signals: Signal names to resolve (from R1PolicySpec.regime_signals).
        merged_kg: Working KG for KG-level signal queries.
        collections: Per-asset MarketStateCollections for state-level queries.
        assets: Assets to scope signal queries to.

    Returns:
        Dict mapping each signal name to its resolved boolean value.
    """
    result: dict = {}
    for name in signals:
        resolver = _REGIME_RESOLVERS.get(name)
        result[name] = resolver(merged_kg, collections, assets) if resolver else False
    return result


# ---------------------------------------------------------------------------
# RegimeDominanceChecker — stateless evaluator
# ---------------------------------------------------------------------------

class RegimeDominanceChecker:
    """Stateless evaluator for an R1PolicySpec against a pre-resolved regime state.

    Separation of concerns:
      - Resolving regime signals (KG queries) is the caller's responsibility.
      - This class only decides whether the resolved booleans satisfy the spec
        and, if so, appends a structured suppression log entry.

    Typical use: instantiate once per chain type at module level, then call
    should_suppress() at chain-activation time.
    """

    def __init__(self, spec: R1PolicySpec) -> None:
        """Store the policy spec; no side effects."""
        self.spec = spec

    def should_suppress(
        self,
        regime_states: dict,
        pair: str,
        log: list,
    ) -> bool:
        """Evaluate R1 and, if suppressing, append a log entry.

        Args:
            regime_states: Resolved {signal_name: bool} dict.  Keys must match
                spec.regime_signals.  Missing keys are treated as False.
            pair: Pair string (e.g. "HYPE/SOL") for the suppression log.
            log: Mutable suppression log; one entry appended when suppressing.

        Returns:
            True if the chain should be suppressed (caller must return early).
            False if the chain should proceed normally.
        """
        s = self.spec
        values = [regime_states.get(sig, False) for sig in s.regime_signals]
        dominant = all(values) if s.regime_combinator == "AND" else any(values)
        if not dominant:
            return False
        entry: dict = {
            "chain": s.chain_type,
            "pair": pair,
            "reason": "contradictory_evidence",
            "detail": s.suppression_reason,
            "neg_evidence_taxonomy": "contradictory_evidence",
            # Always set — identifies any R1-triggered suppression entry regardless
            # of which chain fired. Filter with e.get("r1_regime_dominance_gate").
            "r1_regime_dominance_gate": True,
            "r1_chain_type": s.chain_type,
            "r1_regime_signals": list(s.regime_signals),
            "r1_expected_outcome": s.expected_outcome,
            "r1_contradicting_outcome": s.contradicting_outcome,
        }
        # Chain-specific alias for backward compat (e.g. j1_discriminative_gate for J1).
        # When log_tag is the default "r1_regime_dominance_gate" this is a no-op.
        if s.log_tag != "r1_regime_dominance_gate":
            entry[s.log_tag] = True
        log.append(entry)
        return True


# ---------------------------------------------------------------------------
# apply_r1 — convenience single-call interface
# ---------------------------------------------------------------------------

def apply_r1(
    spec: R1PolicySpec,
    merged_kg: KGraph,
    collections: dict,
    assets: list,
    pair: str,
    log: list,
) -> bool:
    """Apply an R1 policy spec in one call; returns True if chain should be suppressed.

    This is the idiomatic interface for chain builders that want to use R1
    without managing a RegimeDominanceChecker instance explicitly.

    The function resolves regime signals from merged_kg/collections using the
    registered resolvers (see register_regime_resolver), then delegates to
    RegimeDominanceChecker.should_suppress.

    Args:
        spec: R1PolicySpec defining the gate conditions.
        merged_kg: Working KG for KG-level signal resolution.
        collections: Per-asset MarketStateCollections for state-level resolution.
        assets: Assets in scope for signal queries (e.g. [a1, a2]).
        pair: Pair string for the suppression log.
        log: Mutable suppression log; one entry appended when suppressing.

    Returns:
        True → caller must return early (chain suppressed).
        False → chain proceeds normally.
    """
    regime_states = resolve_regime_states(spec.regime_signals, merged_kg, collections, assets)
    checker = RegimeDominanceChecker(spec)
    return checker.should_suppress(regime_states, pair, log)


# ---------------------------------------------------------------------------
# regime_dominance_gate — declarative decorator for future chains
# ---------------------------------------------------------------------------

def regime_dominance_gate(
    *,
    chain_type: str,
    regime_signals: list,
    regime_combinator: str = "AND",
    expected_outcome: str = "",
    contradicting_outcome: str = "",
    suppression_reason: str = "",
) -> Callable:
    """Decorator factory: wrap a chain builder with an automatic R1 check.

    The decorated function must match the standard chain builder signature:
        fn(kg, merged_kg, collections, a1, a2, corr_nid, break_score, log)

    The decorator resolves regime signals from merged_kg and collections,
    checks R1 suppression, and returns early (without calling the chain body)
    if suppression is triggered.

    The spec is attached to the wrapper as `._r1_spec` for introspection.

    Args:
        chain_type: Chain identifier (stored in spec and log).
        regime_signals: Signal names to check (see module docstring for builtins).
        regime_combinator: "AND" (default) or "OR".
        expected_outcome: Informational; the chain's normal outcome label.
        contradicting_outcome: Informational; the regime-dominant outcome label.
        suppression_reason: Overrides auto-generated log detail text.

    Example:
        @regime_dominance_gate(
            chain_type="e1_persistent_aggression",
            regime_signals=["funding_extreme", "oi_accumulation"],
            expected_outcome="beta_reversion",
            contradicting_outcome="positioning_unwind",
        )
        def _e1_persistent_aggression_chain(kg, merged_kg, collections,
                                            a1, a2, corr_nid, break_score, log):
            ...  # R1 check happens before this body executes
    """
    spec = R1PolicySpec(
        chain_type=chain_type,
        regime_signals=regime_signals,
        regime_combinator=regime_combinator,
        expected_outcome=expected_outcome,
        contradicting_outcome=contradicting_outcome,
        suppression_reason=suppression_reason,
    )
    checker = RegimeDominanceChecker(spec)

    def decorator(fn: Callable) -> Callable:
        @functools.wraps(fn)
        def wrapper(kg, merged_kg, collections, a1, a2, corr_nid, break_score, log):
            regime_states = resolve_regime_states(
                spec.regime_signals, merged_kg, collections, [a1, a2]
            )
            if checker.should_suppress(regime_states, f"{a1}/{a2}", log):
                return
            return fn(kg, merged_kg, collections, a1, a2, corr_nid, break_score, log)

        # Attach spec for introspection / testing
        wrapper._r1_spec = spec  # type: ignore[attr-defined]
        return wrapper

    return decorator
